<a href="https://colab.research.google.com/github/NeoAnushka21/Practice_Models_Anushka/blob/main/data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
dataset=pd.read_csv('Data(1).csv')
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1]

In [ ]:
print(X)

[['8th Class' 12.0 90.0]
 ['9th class' 11.0 85.0]
 ['7th class' 13.0 nan]
 ['7th class' 11.0 53.0]
 ['9th class' 12.0 45.0]
 ['8th Class' 12.0 33.0]
 ['8th Class' 10.0 63.0]
 ['7th class' 14.0 89.0]
 ['9th class' 12.0 30.0]
 ['8th Class' nan 42.0]
 ['9th class' 11.0 67.0]
 ['7th class' 13.0 31.0]
 ['7th class' 12.0 45.0]
 ['8th Class' 13.0 32.0]
 ['9th class' 14.0 nan]
 ['9th class' 11.0 64.0]
 ['7th class' nan 34.0]
 ['8th Class' 9.0 51.0]
 ['9th class' 10.0 73.0]
 ['7th class' 9.0 88.0]]


In [ ]:
print(y)

0     pass
1     pass
2     pass
3     pass
4     pass
5     fail
6     pass
7     pass
8     fail
9     pass
10    pass
11    fail
12    pass
13    fail
14    pass
15    pass
16    fail
17    pass
18    pass
19    pass
Name: Result, dtype: object


In [ ]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

In [ ]:
print(X)

[['8th Class' 12.0 90.0]
 ['9th class' 11.0 85.0]
 ['7th class' 13.0 56.388888888888886]
 ['7th class' 11.0 53.0]
 ['9th class' 12.0 45.0]
 ['8th Class' 12.0 33.0]
 ['8th Class' 10.0 63.0]
 ['7th class' 14.0 89.0]
 ['9th class' 12.0 30.0]
 ['8th Class' 11.61111111111111 42.0]
 ['9th class' 11.0 67.0]
 ['7th class' 13.0 31.0]
 ['7th class' 12.0 45.0]
 ['8th Class' 13.0 32.0]
 ['9th class' 14.0 56.388888888888886]
 ['9th class' 11.0 64.0]
 ['7th class' 11.61111111111111 34.0]
 ['8th Class' 9.0 51.0]
 ['9th class' 10.0 73.0]
 ['7th class' 9.0 88.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[1 1 1 1 1 0 1 1 0 1 1 0 1 0 1 1 0 1 1 1]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
print(X_train)

[[1.0 0.0 0.0 13.0 56.388888888888886]
 [0.0 0.0 1.0 14.0 56.388888888888886]
 [0.0 0.0 1.0 12.0 45.0]
 [0.0 1.0 0.0 9.0 51.0]
 [1.0 0.0 0.0 14.0 89.0]
 [0.0 0.0 1.0 11.0 85.0]
 [0.0 1.0 0.0 13.0 32.0]
 [0.0 1.0 0.0 12.0 90.0]
 [1.0 0.0 0.0 9.0 88.0]
 [0.0 0.0 1.0 10.0 73.0]
 [0.0 1.0 0.0 11.61111111111111 42.0]
 [0.0 0.0 1.0 11.0 64.0]
 [0.0 0.0 1.0 12.0 30.0]
 [1.0 0.0 0.0 12.0 45.0]
 [1.0 0.0 0.0 13.0 31.0]
 [0.0 1.0 0.0 12.0 33.0]]


In [ ]:
print(X_test)

[[1.0 0.0 0.0 11.0 53.0]
 [1.0 0.0 0.0 11.61111111111111 34.0]
 [0.0 1.0 0.0 10.0 63.0]
 [0.0 0.0 1.0 11.0 67.0]]


In [ ]:
print(y_train)

[1 1 1 1 1 1 0 1 1 1 1 1 0 1 0 0]


In [ ]:
print(y_test)

[1 0 1 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [ ]:
print(X_train)

[[1.0 0.0 0.0 0.826043022729018 -0.025001877899628218]
 [0.0 0.0 1.0 1.507706032889354 -0.025001877899628218]
 [0.0 0.0 1.0 0.1443800125686821 -0.5575094071904046]
 [0.0 1.0 0.0 -1.9006090179123256 -0.2769688551738004]
 [1.0 0.0 0.0 1.507706032889354 1.4997879742646931]
 [0.0 0.0 1.0 -0.5372829975916538 1.3127609395869568]
 [0.0 1.0 0.0 0.826043022729018 -1.1653472698930472]
 [0.0 1.0 0.0 0.1443800125686821 1.546544732934127]
 [1.0 0.0 0.0 -1.9006090179123256 1.453031215595259]
 [0.0 0.0 1.0 -1.2189460077519896 0.7516798355537485]
 [0.0 1.0 0.0 -0.12071115804922655 -0.6977796831987068]
 [0.0 0.0 1.0 -0.5372829975916538 0.33086900752884213]
 [0.0 0.0 1.0 0.1443800125686821 -1.2588607872319153]
 [1.0 0.0 0.0 0.1443800125686821 -0.5575094071904046]
 [1.0 0.0 0.0 0.826043022729018 -1.2121040285624811]
 [0.0 1.0 0.0 0.1443800125686821 -1.1185905112236132]]


In [ ]:
print(X_test)

[[1.0 0.0 0.0 -0.5372829975916538 -0.1834553378349323]
 [1.0 0.0 0.0 -0.12071115804922655 -1.071833752554179]
 [0.0 1.0 0.0 -1.2189460077519896 0.28411224885940806]
 [0.0 0.0 1.0 -0.5372829975916538 0.47113928353714424]]
